### PR TITLE
implemented more stats (collapsible)

### PR DESCRIPTION
**Pull request by huttarl**

### CODE REVIEW

**Comment by levskaya** [comment]
I just realized that I somehow deleted the code for the 'hollow' operator some time ago.  I've put that back in, so 'h' should work now.  I really love the new chamfer operator!  I should definitely see if it can be parametrized so that a gentle version of it can be applied to super-complicated geometries.  Thanks again so much for the help!

**Comment by huttarl** [comment]
Yeah, I was thinking about that too... but I will leave it to you if you think you'll work on it soon.

Meanwhile I may take a whack at the 'whirl' or the 'half' (alternation) operator. For the latter, Coxeter uses an 'h' prefix, so we'd have to decide how to handle the collision with 'h' standing for 'hollow'.

**Comment by huttarl** [comment]
P.S. Glad you like the chamfer! Thanks for being open to collaborating.

**Comment by levskaya** [comment]
I'm not sure that I'll be able to work on parametrizing chamfer too soon - so if you feel like it I'd say go ahead.  Hmm... maybe we can just call hollow 'x'.

**Comment by levskaya** [comment]
oh right, 'x' is used already... maybe, since hollow is weird, just call it 'H' caps, and keep the classical operators lower case, so we can switch w to h to keep Coxeter's notation.

**Comment by huttarl** [comment]
'H' for hollow and 'h' for alternation -- sounds good.
'w' (whirl) is a separate animal -- let's keep that as 'w', OK?

**Pull request merged**
